version: 1.0.{build}

image: Visual Studio 2022

configuration: Release

branches:
  only:
    - main

before_build:
  - dotnet --info
  - dotnet restore ILoggerSample.sln

build_script:
  - dotnet build ILoggerSample.sln --configuration Release --no-restore

test: off
